<?php
/*
------------------
Language: English
------------------
*/

$lang = array();

require('menue_includes/top_menue.php');
require('menue_includes/A_left_menue.php');

$lang['C3_00']        = 'This text is currently only available in German language';

$lang['C3_1_header']  = 'AGB / Allgemeine Vertragsbedingungen (AVB) der 3appy UG (haftungsbeschr&#228nkt)';
$lang['C3_2_header']  = '&#167 1 Vertragsinhalt';
$lang['C3_2_1']       = '<ol><li>Es gelten ausschlie&#223lich die Vertragsbedingungen von 3appy. Andere Bedingungen werden nicht Vertragsinhalt, auch wenn 3appy ihnen nicht ausdr&#252cklich widerspricht.</li><li>Vertragserg&#228nzungen und -&#228nderungen bed&#252rfen stets der Schriftform.</li><li>Auch wenn beim Abschluss weiterer Vertr&#228ge hierauf nicht nochmals hingewiesen wird, gelten die AVB von 3appy im kaufm&#228nnischen Verkehr in ihrer jeweils geltenden Fassung.</li><li>Darstellungen in Testprogrammen, Produkt- und Projektbeschreibungen bedeuten keine Garantie oder &#220bernahme sonstigem Risikos.</li><li>Der Auftraggeber hat gepr&#252ft, dass die Spezifikation der Vertragsgegenst&#228nde seinen W&#252nschen und Bed&#252rfnissen entspricht.</li></ol>';
$lang['C3_3_header']  = '&#167 2 Vertragsgegenst&#228nde';
$lang['C3_3_1']       = '<ol><li>Gegenstand des Kaufvertrages &#252ber Standardprodukte ist die &#220berlassung von Standardsoftware und/oder Datenbest&#228nden (im Folgenden: Vertragsgegenst&#228nde).</li><li>Gegenstand des Werkvertrages ist die Realisierung individueller Konzepte.</li></ol>';
$lang['C3_4_header']  = '&#167 3 Zustandekommen des Vertrages';
$lang['C3_4_1']       = '<ol><li>Soweit nicht abweichend vereinbart, kommt der Vertrag durch Antrag des Kunden und Annahme durch 3appy UG zustande. 3appy UG kann den Antrag des Kunden auch durch Bereitstellung der beauftragten Leistung (z.B. Freischaltung des Zuganges) annehmen.</li></ol>';
$lang['C3_5_header']  = '&#167 4 Urheberrecht und geistiges Eigentum';
$lang['C3_5_1']       = '<ol><li>Alle Rechte an der Software (Programm und Handbuch, ggfs. in elektronischer Form) und den Datenbest&#228nden stehen im Verh&#228ltnis der Vertragspartner zueinander ausschlie&#223lich 3appy zu.</li><li>Der Aufraggeber erh&#228lt die nicht ausschlie&#223liche Befugnis, die Vertragsgegenst&#228nde in seinem Betrieb f&#252r eigene Zwecke wie in den mitgelieferten Handb&#252chern und in Abs. 3 - 7 beschrieben zu nutzen.</li><li>Der Aufraggeber darf die Anzahl der Profile (Sch&#228ler) bis zum vertraglig vereinbarten Maximum nutzen. Bei &#220berschreitung der vertraglich vereinbarten Anzahl von Sch&#252lern, wird ohne Ank&#252ndigung die Beitragsstufe der zum Zeitpunkt g&#252ltigen Preisliste abgerechnet.</li><li>Der Auftraggeber hat keinen Anspruch auf Herausgabe von Quellprogrammen.</li><li>Soweit  es sich bei dem Vertragsgegenstand um eine Testversion handelt, erh&#228lt der Auftraggeber entsprechend den Angaben in den Lizenzbedingungen lediglich ein eingeschr&#228nktes Nutzungsrecht. Die Einschr&#228nkungen k&#246nnen den r&#228umlichen Einsatzbereich, die zeitliche Dauer sowie den Inhalt betreffen.</li></ol>';
$lang['C3_6_header']  = '&#167 5 Mitwirkung des Kunden';
$lang['C3_6_1']       = 'Der Auftraggeber unterst&#252tzt 3appy bei der Vertragsdurchf&#252hrung, er sorgt f&#252r Hardware, Betriebssystem und Basissoftware und stellt Telekommunikationseinrichtungen und die erforderliche Anzahl von Mitarbeitern zur Verf&#252gung.';
$lang['C3_7_header']  = '&#167 6 Lieferung und Verz&#246gerung';
$lang['C3_7_1']       = '<ol><li>Angaben zum Lieferzeitpunkt sind unverbindlich. Verbindliche Liefertermine bed&#252rfen der schriftlichen Zusage von 3appy. Teillieferungen sind zul&#228ssig.</li><li>Liefer- und Leistungsfristen verl&#228ngern sich um den Zeitraum, in dem 3appy durch Arbeitsk&#228mpfe, h&#246here Gewalt, Nichtbelieferung durch Zulieferer, Krankheit von Mitarbeitern oder sonstige unvorhergesehene Ereignisse unverschuldet daran gehindert ist, die Lieferung oder Leistung zu erbringen und um einen angemessenen Zeitraum zum Wiederanlaufen nach Ende der St&#246rung. Gleiches gilt, wenn 3appy auf Informationen oder Mitwirkungshandlungen des Auftraggebers wartet.</li><li>Alle Mahnungen und Fristsetzungen des Auftraggebers bed&#252rfen zur Wirksamkeit der Schriftform. Ger&#228t 3appy mit einer Lieferung in Verzug, so entstehen Anspr&#252che, gleich welcher Art, erst ab dem fruchtlosen Ablauf einer Nachfrist, die mindestens 12 Arbeitstage betragen muss.</li></ol>';
$lang['C3_8_header']  = '&#167 7 Widerrufsbelehrung ';
$lang['C3_8_1']       = '<ol><li>Widerrufsrecht Sie k&#246nnen Ihre Vertragserkl&#228rung innerhalb von vierzehn Tage ohne Angabe von Gr&#252nden in Textform (per E-Mail) widerrufen. Die Widerrufsfrist betr&#228gt vierzehn Tage ab dem Tag des Vertragsabschlusses. Zur Wahrung der Widerrufsfrist gen&#252gt die rechtzeitige Absendung des Widerrufs. Der Widerruf ist zu richten an: <a href="mailto:Support@3appy.com?Subject=Support" target="_top">Support@3appy.com</a>.</li></ol>';
$lang['C3_9_header']  = '&#167 8 Zahlung, Aufrechnung und Abtretung';
$lang['C3_9_1']       = '<ol><li>Zahlungen sind ohne Abzug innerhalb von 14 Tagen nach Eingang der Rechnung und der Lieferung f&#228llig. Der Zinssatz f&#252r F&#228lligkeits- und Verzugszinsen betr&#228gt 3 Prozentpunkte &#252ber dem jeweiligen Basiszins der EZB. Der Auftraggeber kann einen niedrigeren, 3appy einen h&#246heren Schaden nachweisen.</li><li>Der Auftraggeber kann nur mit unbestrittenen oder rechtskr&#228ftig festgestellten Forderungen aufrechnen. Er darf gegen 3appy gerichtete Anspr&#252che nicht abtreten; 3appy kann in jedem Fall durch Leistung an den Auftraggeber erf&#252llen (&#167 354 a HGB). Ein Zur&#252ckbehaltungsrecht kann sich nur auf Anspr&#252chen aus diesem Vertrag st&#252tzen.</li></ol>';
$lang['C3_10_header'] = '&#167 9 Eigentumsvorbehalt und Widerrufsvorbehalt';
$lang['C3_10_1']      = '<ol><li>S&#228mtliche Lieferungen von 3appy erfolgen unter der aufschiebenden Bedingung der vollst&#228ndigen Kaufpreiszahlung. 3appy &#252bertr&#228gt die Nutzungsrechte gem&#228&#223 &#167 3 in Verbindung mit dem im Vertrag genannten Lizenzbedingungen unter der aufl&#246senden Bedingung, dass die Forderung von 3appy endg&#252ltig nicht vollst&#228ndig ausgeglichen werden. Der Auftraggeber hat 3appy unverz&#252glich schriftlich zu benachrichtigen, wenn Dritte auf die Software von 3appy oder Datenbest&#228nde zugreifen wollen.</li><li>Au&#223erdem kann 3appy die Nutzungsbefugnisse widerrufen, wenn der Auftraggeber die Nutzungsbeschr&#228nkungen der dem Vertrag beiliegenden Lizenzbedingungen und &#167 3 nicht einh&#228lt oder gegen die Geheimhaltungspflicht des &#167 12 verst&#246&#223t und diese Verhaltensweise auch auf schriftliche Abmahnung mit Widerrufsandrohung nicht sofort unterl&#228sst.</li></ol>';
$lang['C3_11_header'] = '&#167 10 Annahme der Lieferung oder Leistung';
$lang['C3_11_1']      = '<ol><li>Nach Lieferung der Vertragsgegenst&#228nde kann 3appy vom Auftraggeber eine schriftliche Erkl&#228rung des Inhalts verlangen, dass die Lieferung oder Leistung richtig, vollst&#228ndig und mangelfrei ist. Die Erkl&#228rung ist binnen zwei Wochen nach Lieferung abzugeben und darf nur verweigert werden, wenn die Software oder die Datenbest&#228nde betriebsverhindernde oder wesentliche betriebsbehindernde M&#228ngel hat. Die Annahme gilt als erkl&#228rt, wenn der Auftraggeber die Software oder Datenbest&#228nde l&#228nger als vier Wochen seit der Lieferung in Besitz hat, ohne der Annahme entgegenstehende M&#228ngel gem&#228&#223 &#167 9 Abs. 1 zu r&#252gen, oder wenn er ohne Vorbehalt bezahlt.</li><li>Nach erhalt der Zugangsdaten kann der Auftraggeber die Software vier Wochen testen (Probebetrieb). Auftretende M&#228ngel wird der Auftraggeber 3appy unverz&#252glich schriftlich anzeigen. M&#228ngel sind 3appy schriftlich anzuzeigen und werden im Rahmen der Gew&#228hrleistung behoben. Die Annahme gilt als erfolgt, wenn der Auftraggeber zwei Wochen nach Ablauf des Probebetriebes 3appy gegen&#252ber die Verweigerung der Annahme nicht schriftlich erkl&#228rt hat.</li></ol>';
$lang['C3_12_header'] = '&#167 11 Gew&#228hrleistung';
$lang['C3_12_1']      = '<ol><li>Unbeschadet sonstiger gesetzlicher Anforderungen hat der Auftraggeber offensichtliche M&#228ngel innerhalb einer angemessenen Frist schriftlich mit genauer Beschreibung des Fehlers zu r&#252gen. Versp&#228tete, unzureichende oder unbegr&#252ndete R&#252gen befreien 3appy von ihren Leistungspflichten. Soweit 3appy dennoch t&#228tig wird, stellt 3appy den Aufwand in Rechnung.</li><li>3appy leistet Gew&#228hr daf&#252r, dass die Programmfunktionen frei von Sachm&#228ngeln sind. Dies ist der Fall, wenn sie sich f&#252r die nach dem Vertrag vorausgesetzte bzw. f&#252r die gew&#246hnliche Verwendung eignen bzw. eine Beschaffenheit aufweisen, die bei Werken der gleichen Art &#252blich ist und die der Besteller nach Art des Werkes erwarten kann.</li><li>Der Auftraggeber unterst&#252tzt 3appy bei der M&#228ngelbeseitigung (&#220berlassen von Fehlerbeschreibungen und Testdaten, Ausk&#252nfte der Mitarbeiter usw.). Der Auftraggeber wird angemessene Vorkehrungen f&#252r den Fall treffen, dass die Software ganz oder teilweise nicht ordnungsgem&#228&#223 arbeitet, und zwar insbesondere durch Datensicherung, St&#246rungsdiagnose, laufende &#220berpr&#252fung etc..</li><li>Falls die Nachbesserung endg&#252ltig fehlgeschlagen ist, hat der Auftraggeber das Recht, die Verg&#252tung herabzusetzen oder den Vertrag r&#252ckg&#228ngig zu machen. F&#252r Schadensersatz gilt &#167 10. Aufwendungen f&#252r eine Mangelbeseitigung durch Dritte oder Vertragskosten schuldet 3appy in keinem Fall. Andere Gew&#228hrleistungsanspr&#252che sind ausgeschlossen.</li><li>3appy wird den Auftraggeber bei der Fehlersuche und -beseitigung auch dann unterst&#252tzen, wenn ein Mangel der 3appy-Lieferungen und Leistungen nicht feststeht. Wenn sich die Lieferungen und Leistungen der 3appy nicht als mangelhaft herausstellen, stellt 3appy den Aufwand in Rechnung.</li><li>Die Gew&#228hrleistung erlischt, wenn die Vertragsgegenst&#228nde ver&#228ndert wurden und der Auftraggeber nicht beweist, dass der Mangel hiervon unabh&#228ngig ist. 3appy leistet au&#223erdem solange keine Gew&#228hr, solange der Auftraggeber die Vertragsgegenst&#228nde entgegen den Nutzungsbeschr&#228nkungen der Lizenzbedingungen und &#167 3 AVB nutzt.</li><li>Die Gew&#228hrleistungszeit beginnt nach der Annahme und dauert 1 Jahr, soweit in den Lizenzbedingungen nichts anderes vereinbart ist.</li></ol>';
$lang['C3_13_header'] = '&#167 12 Haftung';
$lang['C3_13_1']      = '3appy leistet keinen Schadensersatz, gleich aus welchem Rechtsgrund (z. B. Nichterf&#252llung, Unm&#246glichkeit, Verzug, Gew&#228hrleistung, Verschulden bei Vertragsschluss, Nebenpflichtverletzung oder unerlaubter Handlung).';
$lang['C3_14_header'] = '&#167 13 Rechte Dritter';
$lang['C3_14_1']      = '3appy versichert, dass der &#220bertragung von Rechten entsprechend den vorliegenden Vertr&#228gen keine Rechte Dritter entgegenstehen. Falls Dritte entgegenstehende Schutzrechte gegen den Auftraggeber geltend machen, unterrichtet der Auftraggeber 3appy unverz&#252glich schriftlich. 3appy kann f&#252r den Auftraggeber die Anspr&#252che abwehren oder befriedigen oder dem Auftraggeber die Aufwendungen zur Abwehr der Anspr&#252che Dritter ersetzen.';
$lang['C3_15_header'] = '&#167 14 Geheimhaltung und Verwahrung';
$lang['C3_15_1']      = 'Die Vertragsparteien verpflichten sich, alle ihnen bei der Erbringung der vertraglichen Leistungen bekannt werdenden Informationen, Unterlagen und Daten geheim zuhalten und weder Dritten zug&#228nglich zu machen noch anderweitig zu verwenden. Die Vertragsparteien werden ihre Mitarbeiter, die dienstlich Zugang zu den Vertragsgegenst&#228nden haben, schriftlich auf die Geheimhaltungspflicht hinweisen. Der Auftraggeber verwahrt und sichert Vertragsgegenst&#228nde so, dass ein Missbrauch Dritter ausgeschlossen ist. 3appy wird die ihr vom Auftraggeber &#252berlassenen Daten auf Anforderung l&#246schen und ihr &#252berlassene Unterlagen zur&#252ckgeben oder vernichten.';
$lang['C3_16_header'] = '&#167 15 Schlu&#223bestimmungen';
$lang['C3_16_1']      = '<ol><li>Gerichtsstand f&#252r alle Streitigkeiten im Zusammenhang mit diesem Vertragsverh&#228ltnis ist Flensburg, wenn der Auftraggeber Vollkaufmann oder gleichgestellt ist.</li><li>Schriftformerfordernisse dieses Vertrages sind Wirksamkeitsvoraussetzungen.</li><li>Es gilt ausschlie&#223lich das Recht der Bundesrepublik Deutschland unter Ausschluss des UN-Kaufrechts.</li></ol>';
$lang['C3_17_header'] = 'Stand Mai 2015';
$lang['C3_17_1']      = '3appy UG (haftungsbeschr&#228nkt), Flensburg';
?>

